DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Schedule CASCADE CONSTRAINTS;
DROP TABLE Clients CASCADE CONSTRAINTS;
DROP TABLE Staff CASCADE CONSTRAINTS;
DROP TABLE Desserts CASCADE CONSTRAINTS;
DROP TABLE Drinks CASCADE CONSTRAINTS;

-- Пересоздать таблицы
@sql/create_tables.sql;